### ISSUE TITLE
Update asciicast

### ISSUE THREAD

**Issue by Deshdeepak1** [termux/whatprovides#3]
The first command in both asciinema image and cast is  `whatprovides aapt` which won't work and may confuse people, so its better to update it.

**Comment by kcubeterm** [comment]
`whatprovides aapt ` 
work only when you are in $PREFIX/bin/directory.
Or alternatively you can specify full path or relative path.

**Comment by kcubeterm** [comment]
anyway i will update asciicast 
Thanks ;)

**Comment by Deshdeepak1** [comment]
> work only when you are in $PREFIX/bin/directory.

Oh I forgot you were in bin, you did type ls to list bianries.
