### ISSUE TITLE
A few packaging-related issues

### ISSUE THREAD

**Issue by ghost** [termux/whatprovides#4]
1. Stores the database in `$PREFIX/opt/whatprovides/db`. `/opt` is for "add-ons" and side-loaded stuff. Use `$PREFIX/share/whatprovides/db` instead.
2. File list generation should be platform-independent. So, avoid use of `apt`, `dpkg`, etc. Idea of proper parsing of debfiles you can get from https://github.com/termux/command-not-found/blob/master/update_command_lists.sh.

**Comment by kcubeterm** [comment]
Thanks for review,  these resources help me a lot.

**Comment by ghost** [comment]
Database is now stored in right place, makefile is also rewritten to get rid of the bash script.

**Comment by ghost** [comment]
Closing as implemented now.
