### ISSUE TITLE
version 1.2.0 can no longer search for files that aren't installed

### ISSUE THREAD

**Issue by landfillbaby** [termux/whatprovides#6]
you added a specific check that the file to be searched exists, effectively limiting this to be the same as `dpkg -S`,
but it can still search for packages that aren't installed
this seems like inconsistent behaviour to me
maybe instead it should try searching for any file and only error when the file isn't in the database

**Comment by kcubeterm** [comment]
Database still missing few pkgs. Could you tell us about that files which you can't find in arm.

**Comment by landfillbaby** [comment]
you are misunderstanding. if i have *any* package uninstalled and want to search for its files, i cannot. this was not the case with 1.1.0

**Comment by kcubeterm** [comment]
Alright, issue can be reproduced in arch64 also.
